app_name: AgentML-Profiler
master: local[*]

spark_conf:
  spark.executor.memory: 4g
  spark.driver.memory: 4g
  spark.sql.shuffle.partitions: 8
  spark.driver.maxResultSize: 2g
  spark.ui.enabled: false           # disable Spark UI in experiments
